# Generated by Django 4.2.2 on 2023-07-07 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('limit', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('permit_subject', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('male', '남'), ('female', '여')], default='', max_length=20)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년'), ('5', '5학년')], max_length=20)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='myapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='myapp.student')),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
    ]
